apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
    - imgae: alpine
      name: alpine
      command: ['/bin/sh', '-c']
      args: ['shuf -i 0-100 -n i >> /opt/number.out;']
      volumeMounts:
        - mountPath: /opt
          name: data-volume

  volumes:
    - name: data-volume
      hostPath: # 노드내에 파일시스템
        path: /data
        type: Directory
      # persistentVolumeClaim:
      #   claimName: pvc
