apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue #myapp-green
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 5
  selector:
    matchLabels:
      version: v1 #v2
  template:
    spec:
      containers:
        - name: app-container
          image: myapp-image:1.0
