apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30800
  type: NodePort
