apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list', 'get', 'create', 'update', 'delete']
    resourceNames: ['blue', 'orange'] # 해당 포드명
  - apiGroups: ['']
    resources: ['configMap']
    verbs: ['create']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['create']
