apiVersion: rbac.authorization.k8s.io/v1
kind: RoldBinding
metadata:
  name: devuser-developer-binding
subjects:
  - kind: User
    name: dev-user #config에 정의된 이용자
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer #Role 이름
  apiGroup: rbac.authorization.k8s.io
