apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        kind: front-end
    spec:
      containers:
        - name: nginx-containers
          image: nginx
