apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3 #6
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        kind: front-end
    spec:
      containers:
        - name: nginx-containers
          image: nginx
