apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 #replicas와 비슷 성공횟수
  parallelism: 3 #병렬처리 갯수
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never #Always 기본값이다
  backoffLimit: 25 #몇번까지 재시작할지
