apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    kind: front-end
spec:
  containers:
    - name: nginx-containers
      image: nginx

    # - name: backend-container
    #   image: redis
